# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/T7/AI/shape_based_matching

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/T7/AI/shape_based_matching

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/T7/AI/shape_based_matching/CMakeFiles /Volumes/T7/AI/shape_based_matching//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/T7/AI/shape_based_matching/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shape_based_matching_test

# Build rule for target.
shape_based_matching_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shape_based_matching_test
.PHONY : shape_based_matching_test

# fast build rule for target.
shape_based_matching_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/build
.PHONY : shape_based_matching_test/fast

#=============================================================================
# Target rules for targets named template_creator

# Build rule for target.
template_creator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 template_creator
.PHONY : template_creator

# fast build rule for target.
template_creator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/build
.PHONY : template_creator/fast

line2Dup.o: line2Dup.cpp.o
.PHONY : line2Dup.o

# target to build an object file
line2Dup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/line2Dup.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/line2Dup.cpp.o
.PHONY : line2Dup.cpp.o

line2Dup.i: line2Dup.cpp.i
.PHONY : line2Dup.i

# target to preprocess a source file
line2Dup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/line2Dup.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/line2Dup.cpp.i
.PHONY : line2Dup.cpp.i

line2Dup.s: line2Dup.cpp.s
.PHONY : line2Dup.s

# target to generate assembly for a file
line2Dup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/line2Dup.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/line2Dup.cpp.s
.PHONY : line2Dup.cpp.s

template_creator.o: template_creator.cpp.o
.PHONY : template_creator.o

# target to build an object file
template_creator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/template_creator.cpp.o
.PHONY : template_creator.cpp.o

template_creator.i: template_creator.cpp.i
.PHONY : template_creator.i

# target to preprocess a source file
template_creator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/template_creator.cpp.i
.PHONY : template_creator.cpp.i

template_creator.s: template_creator.cpp.s
.PHONY : template_creator.s

# target to generate assembly for a file
template_creator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/template_creator.dir/build.make CMakeFiles/template_creator.dir/template_creator.cpp.s
.PHONY : template_creator.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shape_based_matching_test.dir/build.make CMakeFiles/shape_based_matching_test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shape_based_matching_test"
	@echo "... template_creator"
	@echo "... line2Dup.o"
	@echo "... line2Dup.i"
	@echo "... line2Dup.s"
	@echo "... template_creator.o"
	@echo "... template_creator.i"
	@echo "... template_creator.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

